In [1]:
import pandas as pd

In [2]:
lista = ["cinema", "museum", "park", "zoo", "japanese",
         "burger", "vietnamese", "tapas", "korean", "brewery",
         "club", "pub", "bowling", "greek", "juices", "vegan",
         "french", "mexican", "asian", "rooftop", "cocktail", 
         "nightlife", "ramen", "argentino", "grill", "italian",
         "thai", "cake", "cupcakes", "coffee", "mid eastern",
         "indian", "pizza", "sweets", "theater", "spa", "ice cream",
         "sports bar", "healthy", "vegetarian", "drinks",
         "jazz", "wine", "karaoke", "dancing", "seafood", "discoteca", "escape room",
         "centro comercial", "pista padel", "pista tenis", "campo de futbol", 
         "paintball", "multiaventura", "cancha baloncesto", "gluten free", 
         "autocine", "cata de vino", "pista de hielo", "senderismo"
         ]

In [7]:
for place in lista:
    name = "data/" + place + ".csv"
    locals()[place] = pd.read_csv(name, index_col=0)

In [9]:
df_names = []
for place in lista:
    df_names.append(locals()[place])

In [12]:
df = pd.concat(df_names, ignore_index=True)

In [15]:
df.shape

(3079, 6)

In [16]:
df.sample(15)

,name,rating,location,address,price_level,place
2221,Karaoke Singer´s House,3.6,"{'type': 'Point', 'coordinates': [-3.657579, 4...","Av. de Moratalaz, 45, 28030 Madrid, Spain",2.0,karaoke
1184,Grazie Mille Kitchen bar,4.1,"{'type': 'Point', 'coordinates': [-3.707516, 4...","Calle Mayor, 31, 28013 Madrid, Spain",2.0,italian
1305,Fika Patisserie Madrid,5.0,"{'type': 'Point', 'coordinates': [-3.672964099...","Calle de Costa Rica, 26, 28016 Madrid, Spain",NaN,cake
2674,Club Mirasierra,4.3,"{'type': 'Point', 'coordinates': [-3.704151, 4...","Calle de la Costa Brava, 8, 28034 Madrid, Spain",NaN,pista tenis
659,Chicken Of the Woods,4.9,"{'type': 'Point', 'coordinates': [-3.7078083, ...","Calle de la Palma, 63, 28015 Madrid, Spain",NaN,vegan
2884,Canchas de baloncesto Arroyopozuelo,0.0,"{'type': 'Point', 'coordinates': [-3.7733528, ...","28023 Madrid, Spain",NaN,cancha baloncesto
1697,Flamenco Essential Flamenco Show,4.7,"{'type': 'Point', 'coordinates': [-3.7027271, ...","Calle de la Cruz, 26, 28012 Madrid, Spain",NaN,theater
2442,El Sol,4.3,"{'type': 'Point', 'coordinates': [-3.7016321, ...","Calle de los Jardines, 3, 28013 Madrid, Spain",NaN,discoteca
417,Viuda de Cortés S.L.,0.0,"{'type': 'Point', 'coordinates': [-3.7245116, ...","Paseo de la Florida, 51, 28008 Madrid, Spain",NaN,brewery
1009,The Dash,4.4,"{'type': 'Point', 'coordinates': [-3.7006417, ...","C/ de Murillo, 5, 28010 Madrid, Spain",2.0,nightlife
211,Naomi,4.6,"{'type': 'Point', 'coordinates': [-3.7006115, ...","Calle de Ávila, 14, 28020 Madrid, Spain",2.0,japanese
1101,Empanadas Malvón,4.6,"{'type': 'Point', 'coordinates': [-3.6824001, ...","Calle de Alcalá, 109, 28009 Madrid, Spain",NaN,argentino
2268,Flow escuela de baile y pole dance EN MADRID,4.6,"{'type': 'Point', 'coordinates': [-3.6998981, ...","Calle de San Germán, 56, 28020 Madrid, Spain",NaN,dancing
2070,Cometapas - Tapas en Madrid,4.0,"{'type': 'Point', 'coordinates': [-3.72473, 40...","Plaza de Coímbra, 4, 28025 Madrid, Spain",1.0,drinks
810,El Chaparrito,4.3,"{'type': 'Point', 'coordinates': [-3.698896599...","Calle de Ventura de la Vega, 11, 28014 Madrid,...",1.0,mexican

**Price Level**      
0 — Free    
1 — Inexpensive      
2 — Moderate        
3 — Expensive      
4 — Very Expensive